### ISSUE TITLE
Proposal simplify steps

### ISSUE THREAD

**Issue by brauliodiez** [vintem/TypescriptMochaWebpackDemo#2]
We could skip having the developer to run tsd and ask node to do that automatically after each "npm install", something like adding to the package.json:

```
{
  "name": "...",
  "scripts": {
    "postinstall": "tsd reinstall --overwrite --save"
  },

```

On the other hand shouldn't be a good idea to add the steps to start from scratch? Something like:
## To get started:
1. Install [NodeJS](http://www.nodejs.org)  
2. `npm install webpack -g` - Installs webpack
3. 'npm install tsd -g' - Installs tsd.
4. Download this repo
5. Open the command line of your choice and cd to the root directory of this repo on your machine  

If you find it useful but you don't have time I'm more than keen into forking and opening a branch with the proposal.

**Comment by thitemple** [comment]
Good idea and the text explaining is a great idea. Would you mind making a pull request?

**Comment by brauliodiez** [comment]
I will do, thanks.
