### ISSUE TITLE
Not working with webpack 2

### ISSUE THREAD

**Issue by piernik** [vintem/TypescriptMochaWebpackDemo#8]
When I updated webpack to 2.1.0-beta.28 Your template stopped working. 
`16 01 2017 14:21:38.644:ERROR [preprocess]: Can not load "webpack"!`

Solution:
1. Proper webpack version is 2.2.0-rc.4
2. in webpack.config.js change to `extensions: ['.ts', '.js', '.tsx', '.jsx']`

**Comment by thitemple** [comment]
I'm sorry, but I have not used Webpack 2 yet

**Comment by Ciantic** [comment]
I wonder if there is other issues with webpack 2, for me I can't make it to discover tests
